# Generated by Django 3.2.4 on 2021-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.TextField(help_text='text of Question for the game', max_length=1000)),
                ('QuestionNum', models.IntegerField(help_text='num of Question for the game')),
                ('BaseText', models.CharField(help_text='Name of Base', max_length=140)),
                ('BaseNum', models.IntegerField(help_text='Number of Base')),
            ],
            options={
                'ordering': ['BaseNum', 'QuestionNum'],
            },
        ),
    ]
