# Generated by Django 3.2.4 on 2022-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charis',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='consti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='dext',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='inte',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Elvish'), ('3', 'Dragon'), ('4', 'Infernal'), ('5', 'Giant'), ('6', 'Abyss')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='character',
            name='stren',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='wisd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
