# Generated by Django 3.2.4 on 2022-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0002_auto_20220310_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='chars/uploads/'),
        ),
    ]
