# Generated by Django 3.2.4 on 2022-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0006_auto_20220310_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cuprum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='maxhp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='charis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='consti',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='dext',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='inte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='languages',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='stren',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisd',
            field=models.IntegerField(default=0),
        ),
    ]
