# Generated by Django 3.2.4 on 2022-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0007_auto_20220311_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Proficiencies',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='Proficiency',
            field=models.IntegerField(default=0),
        ),
    ]
